version: '3'

services:
  pgdb-auth:
    container_name: pgdb-auth
    image: postgres:15
    restart: always
    volumes:
      - pgdbdatas:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5433:5432'
    networks:
      - pg
  pgadmin-auth:
    container_name: pgadmin-auth
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin-auth:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - '8080:80'
    networks:
      - pg
volumes:
  pgdbdatas:
  pgadmin-auth:
networks:
  pg:
    driver: bridge